# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuIOQ4QDoUrhkxJNWZ8sssfloZUogUGV
"""

#QUESTION 3
import numpy as np
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

# Generate Dataset 1: Uniform distribution (0 to 1 on both axes)
n_points1 = 1000
dataset1 = np.random.rand(n_points1, 2)  # 1000 points, 2D

# Generate Dataset 2: Four distinct clusters
n_points2 = 1000 // 4  # 250 points per cluster
cluster_centers = np.array([[2, 2], [4, 2], [6, 2], [4, 0]])
dataset2 = np.vstack([np.random.normal(loc=center, scale=0.2, size=(n_points2, 2)) for center in cluster_centers])

# K-means implementation
def k_means(data, initial_centroids, n_iterations=5):
    centroids = initial_centroids.copy()
    for _ in range(n_iterations):
        # Assignment step: Assign each point to the nearest centroid
        distances = np.array([[np.sum((point - centroid) ** 2) for centroid in centroids] for point in data])
        labels = np.argmin(distances, axis=1)

        # Update step: Recalculate centroids as the mean of assigned points
        new_centroids = np.array([data[labels == k].mean(axis=0) if np.any(labels == k) else centroids[k] for k in range(len(centroids))])

        # Check for convergence (optional, simplified here with fixed iterations)
        centroids = new_centroids
    return labels, centroids

# Dataset 1 Initializations and Results
print("Dataset 1 (Uniform Distribution):")
# Initialization 1: Corners
init_centroids1_1 = np.array([[0.2, 0.2], [0.2, 0.8], [0.8, 0.2], [0.8, 0.8]])
labels1_1, centroids1_1 = k_means(dataset1, init_centroids1_1)
print(f"Initialization 1 Centroids after convergence: {centroids1_1}")

# Initialization 2: Edges
init_centroids1_2 = np.array([[0.1, 0.5], [0.5, 0.9], [0.9, 0.5], [0.5, 0.1]])
labels1_2, centroids1_2 = k_means(dataset1, init_centroids1_2)
print(f"Initialization 2 Centroids after convergence: {centroids1_2}")

# Dataset 2 Initializations and Results
print("\nDataset 2 (Four Clusters):")
# Initialization 1: Cluster centers
init_centroids2_1 = np.array([[2.0, 2.0], [4.0, 2.0], [6.0, 2.0], [4.0, 0.0]])
labels2_1, centroids2_1 = k_means(dataset2, init_centroids2_1)
print(f"Initialization 1 Centroids after convergence: {centroids2_1}")

# Initialization 2: Offset centers
init_centroids2_2 = np.array([[1.5, 1.5], [3.5, 2.5], [5.5, 2.5], [4.5, -0.5]])
labels2_2, centroids2_2 = k_means(dataset2, init_centroids2_2)
print(f"Initialization 2 Centroids after convergence: {centroids2_2}")

# Visualization
plt.figure(figsize=(12, 8))

# Dataset 1 - Initialization 1
plt.subplot(2, 2, 1)
plt.scatter(dataset1[:, 0], dataset1[:, 1], c=labels1_1, cmap='viridis', alpha=0.5)
plt.scatter(centroids1_1[:, 0], centroids1_1[:, 1], c='red', marker='x', s=200, label='Centroids')
plt.title('Dataset 1 - Init 1 (Corners)')
plt.legend()

# Dataset 1 - Initialization 2
plt.subplot(2, 2, 2)
plt.scatter(dataset1[:, 0], dataset1[:, 1], c=labels1_2, cmap='viridis', alpha=0.5)
plt.scatter(centroids1_2[:, 0], centroids1_2[:, 1], c='red', marker='x', s=200, label='Centroids')
plt.title('Dataset 1 - Init 2 (Edges)')
plt.legend()

# Dataset 2 - Initialization 1
plt.subplot(2, 2, 3)
plt.scatter(dataset2[:, 0], dataset2[:, 1], c=labels2_1, cmap='viridis', alpha=0.5)
plt.scatter(centroids2_1[:, 0], centroids2_1[:, 1], c='red', marker='x', s=200, label='Centroids')
plt.title('Dataset 2 - Init 1 (Cluster Centers)')
plt.legend()

# Dataset 2 - Initialization 2
plt.subplot(2, 2, 4)
plt.scatter(dataset2[:, 0], dataset2[:, 1], c=labels2_2, cmap='viridis', alpha=0.5)
plt.scatter(centroids2_2[:, 0], centroids2_2[:, 1], c='red', marker='x', s=200, label='Centroids')
plt.title('Dataset 2 - Init 2 (Offset Centers)')
plt